version: '3.8'

services:
  postgres:
    image: 'postgres:15.4'
    container_name: 'weather_db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=user2'
      - 'POSTGRES_PASSWORD=isYfi53hm8XMqdTY'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=weather'
    restart: always

#in real project you need save credential to environment variables